<h2>Podobieństwo dokumentów</h2>

Weźmy dwa (podobne) dokumenty.

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import sent_tokenize

sentences = ["I eat an apple.", "I ate the apple."]


print(sentences)
vectorizer = CountVectorizer()
vectorizer.fit(sentences)
print( vectorizer.vocabulary_ )
bag_of_words = vectorizer.transform(sentences)
print(bag_of_words.todense())

['I eat an apple.', 'I ate the apple.']
{'eat': 3, 'an': 0, 'apple': 1, 'ate': 2, 'the': 4}
[[1 1 0 1 0]
 [0 1 1 0 1]]


ZADANIE: Policzyć ich odległość (euklidesową i hammminga).

In [33]:
import numpy as np

t1 = np.array(bag_of_words[0].todense()).flatten()
t2 = np.array(bag_of_words[1].todense()).flatten()
print(t1)
print(t2)

import scipy.spatial.distance as dist

print(dist.euclidean(t1,t2))

print(dist.hamming(t1,t2))

[1 1 0 1 0]
[0 1 1 0 1]
2.0
0.8


ZADANIE: Usuńmy stopwords oraz zestemujmy.

In [34]:
#TODO

Cześciowo pomogło. Weźmy inny przykład i policzmy odległość.

In [35]:
sentences = ["I love apples.", "I love apples. I love apples."]


print(sentences)
vectorizer = CountVectorizer()
vectorizer.fit(sentences)
print( vectorizer.vocabulary_ )
bag_of_words = vectorizer.transform(sentences)
print(bag_of_words.todense())

['I love apples.', 'I love apples. I love apples.']
{'love': 1, 'apples': 0}
[[1 1]
 [2 2]]


Liczność słów często nie ma znaczenia. 

ZADANIE: (1) Proszę użyć odelgłości kosinusowej (2) Proszę użyć reprezentacji set-of-words.

In [36]:


from scipy.spatial.distance import cosine
print(cosine(t1,t2))

0.666666666667


Odległość cosinsusowa jest typową odległością na tekstach - ważny jest tylko kąt a nie długość.


Dla wyszukiwania informacji w tekstach można użyć odległości cosinusowej